<a href="https://colab.research.google.com/github/IA2122/entregable-1-paochoa/blob/main/Proyecto1_Comparaci%C3%B3nModelos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Tratamiento de datos
# ==============================================================================
import pandas as pd
import numpy as np

# Gráficos
# ==============================================================================
import matplotlib.pyplot as plt
from matplotlib import style
import seaborn as sns

# Preprocesado y modelado
# ==============================================================================
from scipy.stats import pearsonr
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
import statsmodels.api as sm
import statsmodels.formula.api as smf

# Configuración matplotlib
# ==============================================================================
plt.rcParams['image.cmap'] = "bwr"
#plt.rcParams['figure.dpi'] = "100"
plt.rcParams['savefig.bbox'] = "tight"
style.use('ggplot') or plt.style.use('ggplot')

# Configuración warnings
# ==============================================================================
import warnings
warnings.filterwarnings('ignore')
from scipy.io import arff

# Para dividir el conjunto de datos
# ==============================================================================
from sklearn.model_selection import train_test_split

# Para comprobar como de buenos son los algoritmos
# ==============================================================================
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint as sp_randint

# Algoritmos de los modelos
# ==============================================================================
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Las siguientes funciones las usaré para aplicar a la técnica de validación K-fold esos métodos

In [ ]:
def gridsearch(model,parameters,scores,k):
    for score in scores:
        print("# Tuning hyper-parameters for %s" % score)
        print()

        clf = GridSearchCV(model, parameters, cv=k,
                           scoring='%s_macro' % score)
        clf.fit(trainData, trainLabels)

        print("Best parameters set found on development set:")
        print()
        print(clf.best_params_)
        print()
        print("Grid scores on development set:")
        print()
        means = clf.cv_results_['mean_test_score']
        stds = clf.cv_results_['std_test_score']
        for mean, std, params in zip(means, stds, clf.cv_results_['params']):
            print("%0.3f (+/-%0.03f) for %r"
                  % (mean, std * 2, params))
        print()

In [ ]:
def randomsearch(model,parameters,scores,k=5):
    for score in scores:  
      print("# Tuning hyper-parameters for %s" % score)
      print()

      clf = RandomizedSearchCV(model, parameters,cv=k)
      clf.fit(trainData, trainLabels)

      print("Best parameters set found on development set:")
      print()
      print(clf.best_params_)
      print()

--------------------------------------------------------------------------------

In [ ]:
df_train = pd.read_csv('train.csv')

In [ ]:
X =  df_train.values[:,:-1]
Y =  df_train.values[:,-1]


trainData, testData, trainLabels, testLabels = train_test_split(X, Y, test_size=0.2, random_state=0, shuffle=True)

A continuación probaré los siguientes algoritmos para buscar los parámetros que produzcan mayor precisión para los datos de entrenamiento:

 - KNN
 - Árboles de decisión
 - Regresión logística
 - SVM
 - Redes neuronales

 Una vez obtenido dichos parámetros, crearé dicho algoritmo para ver como de bien se ajusta a los datos de testeo.

--------------------------------------------------------------------------------

KNN

In [ ]:
for k in range(1,10,1):
    modelKNN = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(modelKNN,trainData,trainLabels,cv=10)
    print("k=%d, Precisión: %0.2f (+/- %0.2f)" % (k, scores.mean(), scores.std() * 2))

k=1, Precisión: 0.59 (+/- 0.02)
k=2, Precisión: 0.58 (+/- 0.02)
k=3, Precisión: 0.59 (+/- 0.03)
k=4, Precisión: 0.59 (+/- 0.04)
k=5, Precisión: 0.59 (+/- 0.04)
k=6, Precisión: 0.59 (+/- 0.02)
k=7, Precisión: 0.60 (+/- 0.02)
k=8, Precisión: 0.59 (+/- 0.02)
k=9, Precisión: 0.59 (+/- 0.03)


In [ ]:
modelKNNBest = KNeighborsClassifier(n_neighbors= 7)
modelKNNBest.fit(trainData, trainLabels)
predictionsKNNBest = modelKNNBest.predict(testData)
print(classification_report(testLabels, predictionsKNNBest))

              precision    recall  f1-score   support

         0.0       0.73      0.70      0.71       951
         1.0       0.61      0.68      0.65       120
         2.0       0.58      0.66      0.62       588
         3.0       0.54      0.58      0.56       793
         4.0       0.58      0.53      0.55       773
         5.0       0.55      0.46      0.50       375

    accuracy                           0.60      3600
   macro avg       0.60      0.60      0.60      3600
weighted avg       0.61      0.60      0.60      3600



--------------------------------------------------------------------------------
Árboles de decisión

In [ ]:
for samples in range(2,13,1):
    modelArbol = DecisionTreeClassifier(random_state=84, min_samples_split=samples)
    scores = cross_val_score(modelArbol,trainData,trainLabels,cv=10)
    print("samples=%d, Precisión: %0.2f (+/- %0.2f)" % (samples, scores.mean(), scores.std() * 2))

modelArbol.fit(trainData, trainLabels)

samples=2, Precisión: 0.67 (+/- 0.02)
samples=3, Precisión: 0.67 (+/- 0.03)
samples=4, Precisión: 0.67 (+/- 0.03)
samples=5, Precisión: 0.67 (+/- 0.03)
samples=6, Precisión: 0.67 (+/- 0.03)
samples=7, Precisión: 0.67 (+/- 0.02)
samples=8, Precisión: 0.67 (+/- 0.02)
samples=9, Precisión: 0.67 (+/- 0.03)
samples=10, Precisión: 0.67 (+/- 0.02)
samples=11, Precisión: 0.67 (+/- 0.02)
samples=12, Precisión: 0.67 (+/- 0.03)


DecisionTreeClassifier(min_samples_split=12, random_state=84)

Aunque en este caso la variación de min_samples_split no es muy significativa (ya que dan todos una precisión muy similar), no cogeré cualquier número. Esto lo hago ya que siempre es recomendable coger el mejor modelo, pero también el más simple

In [ ]:
modelArbolBest = DecisionTreeClassifier(random_state=84, min_samples_split=2)
modelArbolBest.fit(trainData, trainLabels)
predictionsArbolBest = modelArbolBest.predict(testData)
print(classification_report(testLabels, predictionsArbolBest))

              precision    recall  f1-score   support

         0.0       0.91      0.82      0.86       951
         1.0       0.75      0.79      0.77       120
         2.0       0.68      0.68      0.68       588
         3.0       0.59      0.60      0.59       793
         4.0       0.58      0.60      0.59       773
         5.0       0.54      0.60      0.56       375

    accuracy                           0.68      3600
   macro avg       0.67      0.68      0.68      3600
weighted avg       0.69      0.68      0.68      3600



--------------------------------------------------------------------------------
Regresión Lineal


Para este usaré el método de GridSearch ya que tiene más de un parámetro que buscar

In [ ]:
modelLR = LogisticRegression()
tuned_parameters = [{'solver': ['newton-cg', 'lbfgs'],
                     'penalty': ['l2', 'none'],
                     'C': [0.01, 0.1,1, 10]},
                    {'solver': ['liblinear'],
                     'penalty': ['l2', 'l1'],
                     'C': [0.01, 0.1,1, 10]}]
scores = ['precision', 'recall']

In [ ]:
# Aunque no se le pase nada internamente está entrenando el modelo ya que hace uso de los objetos definidos para el entrenamiento
import time
%time
gridsearch(modelLR,tuned_parameters,scores,5)
# le cuesta 8 minutos ejecutarse

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 9.3 µs
# Tuning hyper-parameters for precision

Best parameters set found on development set:

{'C': 1, 'penalty': 'l2', 'solver': 'newton-cg'}

Grid scores on development set:

0.194 (+/-0.019) for {'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}
0.179 (+/-0.045) for {'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}
0.193 (+/-0.020) for {'C': 0.01, 'penalty': 'none', 'solver': 'newton-cg'}
0.171 (+/-0.038) for {'C': 0.01, 'penalty': 'none', 'solver': 'lbfgs'}
0.196 (+/-0.027) for {'C': 0.1, 'penalty': 'l2', 'solver': 'newton-cg'}
0.171 (+/-0.043) for {'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}
0.193 (+/-0.020) for {'C': 0.1, 'penalty': 'none', 'solver': 'newton-cg'}
0.171 (+/-0.038) for {'C': 0.1, 'penalty': 'none', 'solver': 'lbfgs'}
0.198 (+/-0.031) for {'C': 1, 'penalty': 'l2', 'solver': 'newton-cg'}
0.175 (+/-0.035) for {'C': 1, 'penalty': 'l2', 'solver': 'lbfgs'}
0.193 (+/-0.020) for {'C': 1, 'penalty': 'none', 'solver':

In [ ]:
modelLR = LogisticRegression(random_state=84, C=0.01, penalty='l2', solver='newton-cg')
modelLR.fit(trainData, trainLabels)
predictionsLR = modelLR.predict(testData)
print(classification_report(testLabels, predictionsLR))

              precision    recall  f1-score   support

         0.0       0.31      0.64      0.41       951
         1.0       0.00      0.00      0.00       120
         2.0       0.43      0.09      0.15       588
         3.0       0.30      0.27      0.29       793
         4.0       0.19      0.19      0.19       773
         5.0       0.00      0.00      0.00       375

    accuracy                           0.28      3600
   macro avg       0.21      0.20      0.17      3600
weighted avg       0.26      0.28      0.24      3600



Debido a los malos resultados que da, el algoritmo de decisiones queda descartado como posible modelo.

--------------------------------------------------------------------------------
SVM linear 

In [ ]:
for c in [0.1, 1, 10, 100, 1000]:
    modelSVMLinear = SVC(kernel="linear",random_state=84, C=c)
    scores = cross_val_score(modelSVMLinear,trainData,trainLabels,cv=10)
    print("c=%0.2f, Precisión: %0.2f (+/- %0.2f)" % (c, scores.mean(), scores.std() * 2))

In [ ]:
modelSVMLinealBest = SVC(kernel="linear",random_state=84,C=0.1)
modelSVMLinealBest.fit(trainData, trainLabels)
predictionSVMLinealBest = modelSVMLinealBest.predict(testData)
print(classification_report(testLabels, predictionSVMLinealBest))

 Debido a lo mucho que le cuesta ejecutarse, he decidido descartarlo como posible algoritmo para realizar los modelos

In [ ]:
modelSVMLinealBest = SVC(kernel="linear",random_state=84,)
modelSVMLinealBest.fit(trainData, trainLabels)
predictionSVMLinealBest = modelSVMLinealBest.predict(testData)
print(classification_report(testLabels, predictionSVMLinealBest))

--------------------------------------------------------------------------------
SVM sigmoideo

In [ ]:
modelSVMSigmoid = SVC(kernel="sigmoid",random_state=84)
tuned_parametersSVM = [{'gamma': [1, 2, 3, 5],
                     'coef0': [1, 3, 5, 7],
                     'C': [0.01, 0.1,1, 10]}]
scoresSVM = ['precision', 'recall']

In [ ]:
gridsearch(modelSVMSigmoid,tuned_parametersSVM,scoresSVM,5)

# Tuning hyper-parameters for precision

Best parameters set found on development set:

{'C': 0.01, 'coef0': 1, 'gamma': 1}

Grid scores on development set:

0.047 (+/-0.000) for {'C': 0.01, 'coef0': 1, 'gamma': 1}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 1, 'gamma': 2}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 1, 'gamma': 3}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 1, 'gamma': 5}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 3, 'gamma': 1}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 3, 'gamma': 2}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 3, 'gamma': 3}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 3, 'gamma': 5}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 5, 'gamma': 1}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 5, 'gamma': 2}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 5, 'gamma': 3}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 5, 'gamma': 5}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 7, 'gamma': 1}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 7, 'gamma': 2}
0.047 (+/-0.000) for {'C': 0.01, 'coef0': 7,

In [ ]:
modelSVMSigmoidBest = SVC(kernel="sigmoid", gamma = 1, coef0 = 1, C=0.01)
modelSVMSigmoidBest.fit(trainData, trainLabels)
predictionsSVMSigmoidBest = modelSVMSigmoidBest.predict(testData)
print(classification_report(testLabels, predictionsSVMSigmoidBest))

              precision    recall  f1-score   support

         0.0       0.26      1.00      0.42       951
         1.0       0.00      0.00      0.00       120
         2.0       0.00      0.00      0.00       588
         3.0       0.00      0.00      0.00       793
         4.0       0.00      0.00      0.00       773
         5.0       0.00      0.00      0.00       375

    accuracy                           0.26      3600
   macro avg       0.04      0.17      0.07      3600
weighted avg       0.07      0.26      0.11      3600



Como es una precisión todavía menor que en los árboles de decisión, descarto también este algoritmo como posible modelo.

--------------------------------------------------------------------------------
Perceptron

In [ ]:
modelPerceptron = Perceptron(random_state=84)
tuned_parametersPerceptron = [{'max_iter': [10, 100, 1000, 100000],
                     'eta0': [0.01, 0.1, 1, 10]}]
scoresPerceptron = ['precision', 'recall']

In [ ]:
gridsearch(modelPerceptron,tuned_parametersPerceptron,scoresPerceptron,5)

# Tuning hyper-parameters for precision

Best parameters set found on development set:

{'eta0': 0.01, 'max_iter': 10}

Grid scores on development set:

0.127 (+/-0.126) for {'eta0': 0.01, 'max_iter': 10}
0.122 (+/-0.075) for {'eta0': 0.01, 'max_iter': 100}
0.122 (+/-0.075) for {'eta0': 0.01, 'max_iter': 1000}
0.122 (+/-0.075) for {'eta0': 0.01, 'max_iter': 100000}
0.127 (+/-0.126) for {'eta0': 0.1, 'max_iter': 10}
0.122 (+/-0.075) for {'eta0': 0.1, 'max_iter': 100}
0.122 (+/-0.075) for {'eta0': 0.1, 'max_iter': 1000}
0.122 (+/-0.075) for {'eta0': 0.1, 'max_iter': 100000}
0.127 (+/-0.126) for {'eta0': 1, 'max_iter': 10}
0.122 (+/-0.075) for {'eta0': 1, 'max_iter': 100}
0.122 (+/-0.075) for {'eta0': 1, 'max_iter': 1000}
0.122 (+/-0.075) for {'eta0': 1, 'max_iter': 100000}
0.127 (+/-0.126) for {'eta0': 10, 'max_iter': 10}
0.122 (+/-0.075) for {'eta0': 10, 'max_iter': 100}
0.122 (+/-0.075) for {'eta0': 10, 'max_iter': 1000}
0.122 (+/-0.075) for {'eta0': 10, 'max_iter': 100000}

# Tuning h

In [ ]:
modelPerceptronBest = Perceptron(max_iter=100,eta0=0.01,random_state=84)
modelPerceptronBest.fit(trainData,trainLabels)
predictionPerceptronBest = modelPerceptronBest.predict(testData)
print(classification_report(testLabels, predictionPerceptronBest))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00       951
         1.0       0.00      0.00      0.00       120
         2.0       0.24      0.61      0.34       588
         3.0       0.00      0.00      0.00       793
         4.0       0.20      0.00      0.01       773
         5.0       0.12      0.68      0.21       375

    accuracy                           0.17      3600
   macro avg       0.09      0.21      0.09      3600
weighted avg       0.09      0.17      0.08      3600



Ni aún probando valores de eta0 y max_iter todavía más grandes que los puestos en las celdas anteriores se consigue una mayor precisión.
Dicho esto, descarto este algoritmo como posible modelo.

--------------------------------------------------------------------------------
Redes neuronales

En las redes neuronales, los mejores modelos se crean cuando el número de neuronas de la primera capa es igual al número de variables y el número de neuronas de la última capa es igual al número de salidas posibles. 

En nuestro caso la primera capa tendrá 5 neuronas ya que nuestro dataset tiene 5 variables de entrada. En cuanto a las neuronas de la última capa, en nuestro caso habrá 6.

In [ ]:
modelMLP = MLPClassifier()
randomsearch(modelMLP, {'hidden_layer_sizes': [(5,6), (5,3,6), (5,2,3,6), (5,4,3,6)],
                                         'activation':['identity', 'tanh', 'relu'],
                                         'learning_rate_init': [0.001, 0.01, 0.1],
                                         'momentum': [0.9, 0.95, 0.99]},scores,5)

# Tuning hyper-parameters for precision

Best parameters set found on development set:

{'momentum': 0.9, 'learning_rate_init': 0.01, 'hidden_layer_sizes': (6, 2, 3, 6), 'activation': 'tanh'}

# Tuning hyper-parameters for recall

Best parameters set found on development set:

{'momentum': 0.9, 'learning_rate_init': 0.001, 'hidden_layer_sizes': (6, 4, 3, 6), 'activation': 'relu'}



In [ ]:
modelMLPBest = MLPClassifier(hidden_layer_sizes=(5, 2, 3, 6), learning_rate_init=0.01, momentum=0.9, activation= 'tanh')
modelMLPBest.fit(trainData,trainLabels)
predictionMLPBest = modelMLPBest.predict(testData)
print(classification_report(testLabels, predictionMLPBest))

              precision    recall  f1-score   support

         0.0       0.27      1.00      0.43       951
         1.0       0.47      0.14      0.22       120
         2.0       0.53      0.07      0.13       588
         3.0       0.00      0.00      0.00       793
         4.0       0.00      0.00      0.00       773
         5.0       0.00      0.00      0.00       375

    accuracy                           0.28      3600
   macro avg       0.21      0.20      0.13      3600
weighted avg       0.17      0.28      0.14      3600



Debido a la inestabilidad de los resultados que va dando (debido a que, al no poder fijarse el random_state, los datos se fragmentan de manera distinta cada ejecución) y la precisión tan baja obtenida en la mayoría de los casos, he decidido descartar este modelo.

--------------------------------------------------------------------------------

Como el algoritmo con mayor precisión es el de los árboles de decisión intentaré aplicar métodos de ensemble para mejorar aún más los resultados.

Los métodos de ensemble son algortimos que utilizan múltiples algoritmos de aprendizaje para obtener un rendimiento predictivo que mejore el que podría obtenerse por medio de cualquiera de los algoritmos de aprendizaje individuales que lo constituyen.

Más concretamente para los árboles de decisiones existen los siguientes:
 - Bagging: Procedimiento utilizado para reducir la varianza de un método de aprendizaje estadístico, usado muy frecuentemente con árboles de decisión
 - Random Forest
 - Extreme Trees

In [ ]:
from sklearn.ensemble import BaggingClassifier
mAB = BaggingClassifier(random_state=84)
mAB.fit(trainData, trainLabels)
aux = mAB.predict(testData)
pAB = aux.astype(int)
print(classification_report(testLabels, pAB))

              precision    recall  f1-score   support

         0.0       0.94      0.91      0.93       646
         1.0       0.76      0.76      0.76        70
         2.0       0.70      0.75      0.72       402
         3.0       0.60      0.64      0.62       518
         4.0       0.63      0.62      0.63       501
         5.0       0.71      0.61      0.66       263

    accuracy                           0.73      2400
   macro avg       0.72      0.72      0.72      2400
weighted avg       0.73      0.73      0.73      2400



In [ ]:
from sklearn.ensemble import RandomForestClassifier
mAB = RandomForestClassifier(random_state=84, min_samples_split=2)
mAB.fit(trainData, trainLabels)
pAB = mAB.predict(testData)
print(classification_report(testLabels, pAB))

              precision    recall  f1-score   support

         0.0       0.96      0.95      0.95       646
         1.0       0.81      0.73      0.77        70
         2.0       0.72      0.76      0.74       402
         3.0       0.66      0.69      0.68       518
         4.0       0.65      0.65      0.65       501
         5.0       0.72      0.62      0.67       263

    accuracy                           0.76      2400
   macro avg       0.75      0.73      0.74      2400
weighted avg       0.76      0.76      0.76      2400



In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
mAB2 = ExtraTreesClassifier(random_state=84, min_samples_split=5)
mAB2.fit(trainData, trainLabels)
pAB2 = mAB2.predict(testData)
print(classification_report(testLabels, pAB2))

              precision    recall  f1-score   support

         0.0       0.97      0.98      0.97       646
         1.0       0.81      0.74      0.78        70
         2.0       0.73      0.78      0.76       402
         3.0       0.66      0.70      0.68       518
         4.0       0.69      0.64      0.66       501
         5.0       0.71      0.65      0.68       263

    accuracy                           0.77      2400
   macro avg       0.76      0.75      0.75      2400
weighted avg       0.77      0.77      0.77      2400



Como se puede observar el mejor de todos los métodos de ensemble sobre el algoritmo de los árboles de decisión es el de ExtraTrees, por lo que este será el elegido como modelo.

A continuación probaré distintos hiperparámetros para intentar mejorar aún más (si fuese posible)

In [ ]:
ETC1 = ExtraTreesClassifier(random_state=0, min_samples_split=5, criterion= 'entropy')
ETC1.fit(trainData, trainLabels)
pETC1 = ETC1.predict(testData)
print(classification_report(testLabels, pETC1))

              precision    recall  f1-score   support

         0.0       0.97      0.98      0.97       646
         1.0       0.81      0.74      0.78        70
         2.0       0.74      0.79      0.76       402
         3.0       0.66      0.70      0.68       518
         4.0       0.69      0.64      0.66       501
         5.0       0.72      0.65      0.69       263

    accuracy                           0.77      2400
   macro avg       0.76      0.75      0.76      2400
weighted avg       0.77      0.77      0.77      2400



Aunque en un principio pueda parecer que se han obtenido los mismos resultados, si nos fijamos en el desglose de la precisión, se puede observar que en general, tienen menor precisión que en el caso de arriba.

In [ ]:
#np.setdiff1d(trainData.columns, ["CIRCULATION"])
ETC1 = ExtraTreesClassifier(random_state=0, min_samples_split=6, criterion= 'entropy', max_features= 'log2', bootstrap= True, oob_score= True)
ETC1.fit(trainData, trainLabels)
pETC1 = ETC1.predict(testData)
print(classification_report(testLabels, pETC1))

              precision    recall  f1-score   support

         0.0       0.95      0.98      0.96       646
         1.0       0.81      0.80      0.81        70
         2.0       0.74      0.79      0.76       402
         3.0       0.66      0.71      0.68       518
         4.0       0.69      0.63      0.66       501
         5.0       0.75      0.64      0.69       263

    accuracy                           0.77      2400
   macro avg       0.77      0.76      0.76      2400
weighted avg       0.77      0.77      0.77      2400



In [ ]:
modelETC = ExtraTreesClassifier(random_state=0)
scores = ['precision', 'recall']
gridsearch(modelETC, {'min_samples_split': [3,4,6,5,7,8],
                                         'criterion':['gini', 'entropy'],
                                         'min_samples_leaf': [1,2,3,4],
                                         'max_features': ['log2', 'auto', 'sqrt']},scores,5)

# Tuning hyper-parameters for precision

Best parameters set found on development set:

{'criterion': 'gini', 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 7}

Grid scores on development set:

0.744 (+/-0.018) for {'criterion': 'gini', 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 3}
0.749 (+/-0.018) for {'criterion': 'gini', 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 4}
0.748 (+/-0.018) for {'criterion': 'gini', 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 6}
0.745 (+/-0.021) for {'criterion': 'gini', 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 5}
0.753 (+/-0.019) for {'criterion': 'gini', 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 7}
0.749 (+/-0.022) for {'criterion': 'gini', 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 8}
0.739 (+/-0.021) for {'criterion': 'gini', 'max_features': 'log2', 'min_samples_leaf': 2, 'min_sample

In [ ]:
ETC2 = ExtraTreesClassifier(random_state=0, criterion= 'gini', max_features= 'log2', min_samples_leaf= 1, min_samples_split= 7)
ETC2.fit(trainData, trainLabels)
pETC2 = ETC2.predict(testData)
print(classification_report(testLabels, pETC2))

              precision    recall  f1-score   support

         0.0       0.96      0.98      0.97       646
         1.0       0.82      0.76      0.79        70
         2.0       0.73      0.79      0.76       402
         3.0       0.67      0.70      0.69       518
         4.0       0.68      0.64      0.66       501
         5.0       0.75      0.63      0.69       263

    accuracy                           0.77      2400
   macro avg       0.77      0.75      0.76      2400
weighted avg       0.77      0.77      0.77      2400



--------------------------------------------------------------------------------
A continuación probaré otro método de ensemble de los árboles de decisión llamado xgboost el cuál es uno de los más usados actualmente. Para ello, instalaré e importaré las librerias necesarias

In [ ]:
!pip install xgboost

In [ ]:
import xgboost as xgb
from numpy import array
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [ ]:
train_mat = xgb.DMatrix(trainData, label=trainLabels)
test_mat = xgb.DMatrix(testData, label=testLabels)

 - booster: El tipo de modelo de clasificación usado, por defecto gbtree.

 
 - objective: El tipo de tarea de clasificación que realizaremos. Para clasificación binaria, nuestro caso, especificamos binary:logistic.


 - max_depth: “Profundidad” o número de nodos de bifurcación de los árboles de decisión usados en el entrenamiento. Aunque una mayor profundidad puede devolver mejores resultados, también puede resultar en overfitting (sobre ajuste).


 - eta: La tasa de aprendizaje del modelo. Un mayor valor llega más rápidamente al mínimo de la función objetivo, es decir, a un “mejor modelo”, pero puede “pasarse” de su valor óptimo. En cambio, un valor pequeño puede nunca llegar al valor óptimo de la función objetivo, incluso después de muchas iteraciones. En ambos casos, esto afecta el desempeño de nuestros modelos con nuevos.


 - nthread: El número de hilos computacionales que serán usados en el proceso de entrenamiento. Generalmente se refiere a los núcleos del procesador de tu equipo de cómputo, local o remoto, pero también pueden ser los núcleos de un GPU.


 - nround: El número de iteraciones que se realizarán antes de detener el proceso de ajuste. Un mayor número de iteraciones generalmente devuelve mejores resultados de predicción, pero necesita más tiempo de entrenamiento y conlleva un riesgo de sobre ajuste si son demasiadas rondas.

In [ ]:
parametros = {"booster":"gbtree", "max_depth": 2, "eta": 0.3, "objective": "reg:squarederror", "nthread":2}
rondas = 10
evaluacion = [(test_mat, "eval"), (train_mat, "train")]

In [ ]:
modelo = xgb.train(parametros, train_mat, rondas, evaluacion)

[0]	eval-rmse:2.14218	train-rmse:2.13628
[1]	eval-rmse:1.89334	train-rmse:1.89632
[2]	eval-rmse:1.75371	train-rmse:1.75856
[3]	eval-rmse:1.67555	train-rmse:1.68499
[4]	eval-rmse:1.62466	train-rmse:1.63813
[5]	eval-rmse:1.59575	train-rmse:1.61244
[6]	eval-rmse:1.57699	train-rmse:1.5927
[7]	eval-rmse:1.56608	train-rmse:1.58288
[8]	eval-rmse:1.54855	train-rmse:1.56808
[9]	eval-rmse:1.54109	train-rmse:1.56075


In [ ]:
def metricas(objetivo, prediccion):
    matriz_conf = confusion_matrix(objetivo, prediccion)
    score = accuracy_score(objetivo, prediccion)
    reporte = classification_report(objetivo, prediccion)
    metricas = [matriz_conf, score, reporte]
    return(metricas)

In [ ]:
prediccion = modelo.predict(test_mat)
pred = prediccion.astype(int)

In [ ]:
metricas = metricas(testLabels, pred)
[print(i) for i in metricas]

[[110 400 416  25   0   0]
 [  0  13 107   0   0   0]
 [  0  77 461  50   0   0]
 [  2 105 551 135   0   0]
 [  0  69 550 154   0   0]
 [  0  43 260  72   0   0]]
0.19972222222222222
              precision    recall  f1-score   support

         0.0       0.98      0.12      0.21       951
         1.0       0.02      0.11      0.03       120
         2.0       0.20      0.78      0.31       588
         3.0       0.31      0.17      0.22       793
         4.0       0.00      0.00      0.00       773
         5.0       0.00      0.00      0.00       375

    accuracy                           0.20      3600
   macro avg       0.25      0.20      0.13      3600
weighted avg       0.36      0.20      0.16      3600



[None, None, None]

Como la precisión lo mejora la obtenida con ExtraTreesClassifier, este algoritmo queda descartado como posible solución.